# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /#papers
    weight: 11
  - name: Mentoring
    url: /#talks
    weight: 12
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Teaching
    url: teaching/
    weight: 40
  - name: CV
    url: uploads/resume.pdf
    weight: 20